// Restaurant data - Last updated: 2026-03-26
// Source: Web research from TimeOut Budapest, We Love Budapest, Dining Guide, TripAdvisor
const DATA_LAST_UPDATED = '2026-03-26';
const LAST_WEB_SEARCH = '2026-03-26';

const RESTAURANTS = [
  // === BRUNCH / REGGELI ===
  {
    id: 1,
    name: 'MITZI',
    cuisine: 'Modern magyar, mediterrán',
    mealTypes: ['brunch', 'lunch', 'dinner'],
    address: '1114 Budapest, Bartók Béla út 1.',
    lat: 47.4773,
    lng: 19.0498,
    description: 'Konfitált kacsaszendvicstől bundáskenyéren át gorfiig – újragondolt magyaros és mediterrán fogások egész nap.',
    priceRange: '$$',
    rating: 4.5,
    isNew: false,
    yearInfo: 'Régóta népszerű',
    url: '',
    seafoodWarning: false
  },
  {
    id: 2,
    name: 'Szimply',
    cuisine: 'Kreatív szezonális',
    mealTypes: ['brunch'],
    address: 'Budapest, V. kerület',
    lat: 47.4951,
    lng: 19.0570,
    description: 'Minimalista gyöngyszem a belvárosban, szezonális és mindig friss alapanyagokkal készülő kreatív brunch.',
    priceRange: '$$',
    rating: 4.6,
    isNew: false,
    yearInfo: 'Népszerű',
    url: '',
    seafoodWarning: false
  },
  {
    id: 3,
    name: 'Café Brunch Budapest',
    cuisine: 'Brunch, nemzetközi',
    mealTypes: ['brunch'],
    address: 'Budapest, Belgrád rakpart',
    lat: 47.4881,
    lng: 19.0504,
    description: 'Dunai panorámás brunch a Belgrád rakparton – lenyűgöző kilátás a Gellérthegyre. 2025-ben nyitott új helyszín.',
    priceRange: '$$',
    rating: 4.4,
    isNew: true,
    yearInfo: '2025-ben nyílt új helyszín',
    url: 'https://hu.cafebrunchbudapest.com/',
    seafoodWarning: false
  },
  {
    id: 4,
    name: 'Brunch Bistro Budapest',
    cuisine: 'Reggeli, specialty kávé',
    mealTypes: ['brunch'],
    address: 'Budapest, Bajcsy-Zsilinszky út',
    lat: 47.5015,
    lng: 19.0545,
    description: 'A Bazilika közelében, nagy terasszal – a város egyik legkedveltebb reggelizője.',
    priceRange: '$$',
    rating: 4.5,
    isNew: false,
    yearInfo: 'Népszerű',
    url: 'https://www.brunchbistrobudapest.com/magyar',
    seafoodWarning: false
  },
  {
    id: 5,
    name: 'VAJ',
    cuisine: 'Pékség, brunch',
    mealTypes: ['brunch'],
    address: 'Budapest, József krt. (+ Törökvész, Sas u.)',
    lat: 47.4923,
    lng: 19.0714,
    description: 'Budapest egyik legismertebb újhullámos pékség-lánca – kiemelkedő minőségű pékáruk és reggeli fogások.',
    priceRange: '$',
    rating: 4.4,
    isNew: false,
    yearInfo: 'Népszerű, több helyszín',
    url: '',
    seafoodWarning: false
  },
  {
    id: 6,
    name: 'Déryné Bisztró',
    cuisine: 'Francia-magyar brasserie',
    mealTypes: ['brunch', 'lunch', 'dinner'],
    address: '1013 Budapest, Krisztina tér 3.',
    lat: 47.5032,
    lng: 19.0258,
    description: 'Reggeltől késő estig – pékség, kávézó, brunch- és vacsorahely a Krisztina téren. Elegáns, meghitt hangulat.',
    priceRange: '$$',
    rating: 4.5,
    isNew: false,
    yearInfo: 'Klasszikus kedvenc',
    url: '',
    seafoodWarning: false
  },
  {
    id: 7,
    name: 'Central Grand Café',
    cuisine: 'Történelmi kávéház',
    mealTypes: ['brunch', 'lunch'],
    address: '1053 Budapest, Károlyi utca 9.',
    lat: 47.4924,
    lng: 19.0612,
    description: '7-féle Eggs Benedict variáció, shakshukától a steakes croissant-ig – tradíció és kreativitás elegáns környezetben.',
    priceRange: '$$$',
    rating: 4.3,
    isNew: false,
    yearInfo: 'Legendás',
    url: '',
    seafoodWarning: false
  },
  {
    id: 8,
    name: 'STIKA',
    cuisine: 'Modern brunch',
    mealTypes: ['brunch', 'lunch'],
    address: '1074 Budapest, Dob utca 52.',
    lat: 47.4995,
    lng: 19.0667,
    description: '2014 óta stabil pontja a budapesti brunch-szcénának a Dob utcában.',
    priceRange: '$$',
    rating: 4.4,
    isNew: false,
    yearInfo: '2014 óta',
    url: '',
    seafoodWarning: false
  },
  {
    id: 9,
    name: 'Cirkusz Café',
    cuisine: 'Bohém reggeli',
    mealTypes: ['brunch'],
    address: 'Budapest, VII. kerület',
    lat: 47.4965,
    lng: 19.0604,
    description: 'A bohém reggelizők kedvence – pezsgő hangulat és bőséges „regeneráló reggeli" adagok.',
    priceRange: '$$',
    rating: 4.3,
    isNew: false,
    yearInfo: 'Népszerű',
    url: '',
    seafoodWarning: false
  },
  {
    id: 10,
    name: 'A La Maison Grand',
    cuisine: 'Elegáns brunch',
    mealTypes: ['brunch', 'lunch'],
    address: 'Budapest, Andrássy út környéke',
    lat: 47.5040,
    lng: 19.0620,
    description: 'Vintage stílusú berendezés és prémium alapanyagok – a reggelizés itt elegáns élménnyé válik.',
    priceRange: '$$$',
    rating: 4.5,
    isNew: false,
    yearInfo: 'Prémium',
    url: '',
    seafoodWarning: false
  },
  {
    id: 11,
    name: 'Cziniel Budakeszi',
    cuisine: 'Reggeli, brunch',
    mealTypes: ['brunch'],
    address: 'Budakeszi',
    lat: 47.4750,
    lng: 18.9250,
    description: 'Shakshuka, Eggs Benedict és Huevos Rancheros – 2025 nyarán nyílt, izgalmas brunch Budakeszin.',
    priceRange: '$$',
    rating: 4.3,
    isNew: true,
    yearInfo: '2025 nyarán nyílt',
    url: '',
    seafoodWarning: false
  },
  {
    id: 12,
    name: 'Grumpy',
    cuisine: 'Francia, magyar, marokkói',
    mealTypes: ['brunch', 'lunch'],
    address: 'Budapest, Király utca',
    lat: 47.5000,
    lng: 19.0620,
    description: 'Francia, magyar és marokkói twist a reggeliben és könnyű ebédben – kitűnő ár-érték arány.',
    priceRange: '$',
    rating: 4.4,
    isNew: false,
    yearInfo: 'Népszerű',
    url: '',
    seafoodWarning: false
  },

  // === EBÉD / VACSORA - MAGYAR ===
  {
    id: 13,
    name: 'Stand25',
    cuisine: 'Modern magyar',
    mealTypes: ['lunch', 'dinner'],
    address: '1051 Budapest, Nádor utca',
    lat: 47.5004,
    lng: 19.0486,
    description: 'A klasszikus magyar fogások emelt szintje – Jókai bableves, harcsapaprikás, vaddisznó ragu. Mindig telt ház.',
    priceRange: '$$$',
    rating: 4.7,
    isNew: false,
    yearInfo: 'Kedvenc',
    url: '',
    seafoodWarning: false
  },
  {
    id: 14,
    name: 'Café Kör',
    cuisine: 'Hagyományos magyar',
    mealTypes: ['lunch', 'dinner'],
    address: '1051 Budapest, Sas utca 17.',
    lat: 47.5004,
    lng: 19.0525,
    description: 'Informális hangulat, de kiváló minőség – a business ebéd kedvence. A napi menü hamar elfogy!',
    priceRange: '$$',
    rating: 4.4,
    isNew: false,
    yearInfo: 'Klasszikus',
    url: '',
    seafoodWarning: false
  },
  {
    id: 15,
    name: 'Kiosk',
    cuisine: 'Modern magyar',
    mealTypes: ['lunch', 'dinner'],
    address: '1056 Budapest, Március 15. tér 4.',
    lat: 47.4910,
    lng: 19.0520,
    description: 'Panorámás modern magyar étterem a Duna-parton – több mint egy évtizede népszerű, megújult ételekkel.',
    priceRange: '$$$',
    rating: 4.5,
    isNew: false,
    yearInfo: 'Évek óta népszerű',
    url: '',
    seafoodWarning: false
  },
  {
    id: 16,
    name: 'Gundel',
    cuisine: 'Klasszikus magyar',
    mealTypes: ['lunch', 'dinner'],
    address: '1146 Budapest, Gundel Károly út 4.',
    lat: 47.5155,
    lng: 19.0780,
    description: 'Megfizethető luxus – különösen a vasárnapi ebédmenü kiváló. A Városliget közelsége miatt tökéletes programhoz.',
    priceRange: '$$$',
    rating: 4.3,
    isNew: false,
    yearInfo: 'Legendás, megújult',
    url: '',
    seafoodWarning: false
  },
  {
    id: 17,
    name: 'Szaletly',
    cuisine: 'Modern magyar',
    mealTypes: ['lunch', 'dinner'],
    address: 'Budapest, Városliget közelében',
    lat: 47.5142,
    lng: 19.0752,
    description: 'Elegáns, de laza – gulyás, mangalicás rakott krumpli, bécsi szelet és túrós palacsinta újragondolva.',
    priceRange: '$$',
    rating: 4.4,
    isNew: false,
    yearInfo: 'Népszerű',
    url: '',
    seafoodWarning: false
  },
  {
    id: 18,
    name: 'Kádár Étkezde',
    cuisine: 'Hagyományos magyar',
    mealTypes: ['lunch'],
    address: '1075 Budapest, Klauzál tér 9.',
    lat: 47.4989,
    lng: 19.0655,
    description: 'Négy év szünet után újranyitott legendás étkezde – visszahozta a régi ízeket és a pesti hangulatot.',
    priceRange: '$',
    rating: 4.6,
    isNew: true,
    yearInfo: 'Újranyitott 2025-ben',
    url: '',
    seafoodWarning: false
  },

  // === FINE DINING ===
  {
    id: 19,
    name: 'Babel',
    cuisine: 'Fine dining magyar (Michelin ★)',
    mealTypes: ['dinner'],
    address: '1052 Budapest, Piarista köz 2.',
    lat: 47.4925,
    lng: 19.0548,
    description: 'Michelin-csillagos modern magyar fine dining – 8 és 13 fogásos kóstolómenük az Erzsébet-híd lábánál.',
    priceRange: '$$$$',
    rating: 4.8,
    isNew: false,
    yearInfo: 'Michelin ★',
    url: '',
    seafoodWarning: false
  },
  {
    id: 20,
    name: 'Borkonyha Winekitchen',
    cuisine: 'Magyar, borozó (Michelin ★)',
    mealTypes: ['lunch', 'dinner'],
    address: '1051 Budapest, Sas utca 3.',
    lat: 47.5001,
    lng: 19.0528,
    description: '200+ magyar bor és a legendás tokaji aszús foie gras – Michelin-csillagos, hangulatos nyitott konyha.',
    priceRange: '$$$$',
    rating: 4.7,
    isNew: false,
    yearInfo: 'Michelin ★, 2010 óta',
    url: '',
    seafoodWarning: false
  },
  {
    id: 21,
    name: 'Rumour by Rácz Jenő',
    cuisine: 'Séfasztal fine dining',
    mealTypes: ['dinner'],
    address: 'Budapest, Petőfi tér',
    lat: 47.4920,
    lng: 19.0504,
    description: 'Színház és gasztronómia találkozása – többfogásos degusztációs menü speakeasy hangulatban.',
    priceRange: '$$$$',
    rating: 4.6,
    isNew: false,
    yearInfo: 'Felkapott',
    url: '',
    seafoodWarning: false
  },
  {
    id: 22,
    name: 'Epicurean',
    cuisine: 'Fine dining',
    mealTypes: ['dinner'],
    address: 'Budapest, Óbuda (Goldberger)',
    lat: 47.5350,
    lng: 19.0380,
    description: 'Óbudán nyílt fine dining hely a Goldberger Textilgyár gyönyörű épületegyüttesében.',
    priceRange: '$$$$',
    rating: 4.5,
    isNew: true,
    yearInfo: 'Új, 2025-ben nyílt',
    url: '',
    seafoodWarning: false
  },

  // === OLASZ ===
  {
    id: 23,
    name: 'Trattoria Pomo D\'Oro',
    cuisine: 'Olasz trattoria',
    mealTypes: ['lunch', 'dinner'],
    address: '1051 Budapest, Arany János utca 9.',
    lat: 47.5025,
    lng: 19.0537,
    description: 'Budapest legelismertebb olasz étterme – házi tészták, fatüzelésű kemencés pizza, olasz akadémiai ajánlás.',
    priceRange: '$$$',
    rating: 4.6,
    isNew: false,
    yearInfo: 'Klasszikus',
    url: '',
    seafoodWarning: false
  },
  {
    id: 24,
    name: 'Fausto\'s Ristorante',
    cuisine: 'Olasz fine dining',
    mealTypes: ['lunch', 'dinner'],
    address: '1026 Budapest, Szilágyi Erzsébet fasor 77.',
    lat: 47.5128,
    lng: 19.0215,
    description: 'Kortárs olasz konyha magyar szezonális hozzávalókkal – kifogástalan alapanyagok, letisztult ízek.',
    priceRange: '$$$$',
    rating: 4.7,
    isNew: false,
    yearInfo: '2025-ben új helyre költözött',
    url: '',
    seafoodWarning: false
  },
  {
    id: 25,
    name: 'Ristorante Krizia',
    cuisine: 'Olasz fine dining',
    mealTypes: ['lunch', 'dinner'],
    address: 'Budapest, Mozsár utca',
    lat: 47.5050,
    lng: 19.0625,
    description: 'Eldugott gyöngyszem az Operaház közelében – szezonális, kreatívan megkomponált olasz fine dining.',
    priceRange: '$$$$',
    rating: 4.6,
    isNew: false,
    yearInfo: 'Rejtett kincs',
    url: '',
    seafoodWarning: false
  },
  {
    id: 26,
    name: 'Porcellino Grasso',
    cuisine: 'Olasz, vidékies',
    mealTypes: ['lunch', 'dinner'],
    address: 'Budapest, II. kerület',
    lat: 47.5081,
    lng: 19.0265,
    description: 'Laza, autentikus olasz vidéki stílusú étterem Buda szívében – a helyiek nagy kedvence.',
    priceRange: '$$',
    rating: 4.4,
    isNew: false,
    yearInfo: 'Helyi kedvenc',
    url: 'https://porcellino.hu/',
    seafoodWarning: false
  },
  {
    id: 27,
    name: 'Giulia Budapest',
    cuisine: 'Olasz',
    mealTypes: ['lunch', 'dinner'],
    address: 'Budapest, V. kerület',
    lat: 47.5010,
    lng: 19.0555,
    description: 'Frissen nyílt, kiváló olasz hely – tavasszal kerthelyiség, ősztől belső tér. Ízletes olasz klasszikusok.',
    priceRange: '$$',
    rating: 4.3,
    isNew: true,
    yearInfo: '2025-ben nyílt',
    url: '',
    seafoodWarning: false
  },
  {
    id: 28,
    name: 'Ape Regina',
    cuisine: 'Olasz trattoria',
    mealTypes: ['lunch', 'dinner'],
    address: 'Budapest, Nyugati tér közelében',
    lat: 47.5110,
    lng: 19.0575,
    description: 'Modern olasz trattoria a Nyugati közelében – pizzák, tészták, saláták. Laza ebédre vagy baráti vacsorára tökéletes.',
    priceRange: '$$',
    rating: 4.3,
    isNew: false,
    yearInfo: 'Népszerű',
    url: '',
    seafoodWarning: false
  },

  // === ÁZSIAI / NEMZETKÖZI ===
  {
    id: 29,
    name: '101 Bistro',
    cuisine: 'Tajvani-kínai fúzió',
    mealTypes: ['lunch', 'dinner'],
    address: 'Budapest, Október 6. utca',
    lat: 47.5005,
    lng: 19.0510,
    description: 'Tajvani és kínai ihletésű kis tányérok – pork belly bao, szója-gyömbér csirke, mapo tofu.',
    priceRange: '$$',
    rating: 4.5,
    isNew: false,
    yearInfo: 'Felkapott',
    url: '',
    seafoodWarning: false
  },
  {
    id: 30,
    name: 'Opium',
    cuisine: 'Pán-ázsiai',
    mealTypes: ['lunch', 'dinner'],
    address: 'Budapest, Dob utca',
    lat: 47.4978,
    lng: 19.0610,
    description: 'Zöldellő, meleg fás enteriőr – az egyik legsikeresebb budapesti pán-ázsiai étteremcsoport.',
    priceRange: '$$$',
    rating: 4.4,
    isNew: false,
    yearInfo: 'Sikeres lánc',
    url: '',
    seafoodWarning: true
  },
  {
    id: 31,
    name: '94\' Konyha & Bar',
    cuisine: 'Ázsiai-magyar fúzió (Bib Gourmand)',
    mealTypes: ['lunch', 'dinner'],
    address: 'Budapest, Közraktár utca',
    lat: 47.4860,
    lng: 19.0600,
    description: 'Bib Gourmand díjas – illatos pho, 94\' Gohan, nyitott konyha, és értékalapú „Lunch Break" menü.',
    priceRange: '$$',
    rating: 4.6,
    isNew: true,
    yearInfo: 'Új Bib Gourmand',
    url: '',
    seafoodWarning: false
  },
  {
    id: 32,
    name: 'Kakurega',
    cuisine: 'Japán izakaya, sushi',
    mealTypes: ['dinner'],
    address: 'Budapest, Arany János utca (Opium alagsor)',
    lat: 47.5020,
    lng: 19.0540,
    description: 'Top kategóriás sushibár, rejtett izakaya és ramenező az Opium alatt – 2026 egyik legizgalmasabb új helye.',
    priceRange: '$$$',
    rating: 4.5,
    isNew: true,
    yearInfo: '2026-ban nyílt',
    url: '',
    seafoodWarning: true
  },

  // === ÚJ HELYEK 2025-2026 ===
  {
    id: 33,
    name: 'JUNE',
    cuisine: 'Magyar, közel-keleti',
    mealTypes: ['brunch', 'lunch', 'dinner'],
    address: 'Budapest, MOM Park bejárata',
    lat: 47.4795,
    lng: 19.0185,
    description: 'Egész napos gasztrotér a MOM Parknál – reggel kávé, napközben ebéd, este vacsora. Magyar és közel-keleti inspiráció.',
    priceRange: '$$',
    rating: 4.4,
    isNew: true,
    yearInfo: '2026-ban nyílt',
    url: '',
    seafoodWarning: false
  },
  {
    id: 34,
    name: 'Leopard',
    cuisine: 'Skandináv, pizza',
    mealTypes: ['lunch', 'dinner'],
    address: 'Budapest, Kálvin tér környéke',
    lat: 47.4908,
    lng: 19.0615,
    description: 'Skandináv stílusú hely nápolyi és római pizzákkal a Kálvin tér közelében.',
    priceRange: '$$',
    rating: 4.3,
    isNew: true,
    yearInfo: '2025-ben nyílt',
    url: '',
    seafoodWarning: false
  },
  {
    id: 35,
    name: 'KOLLÁZS Brasserie & Bar',
    cuisine: 'Nemzetközi elegáns',
    mealTypes: ['brunch', 'lunch', 'dinner'],
    address: 'Budapest, Four Seasons Hotel',
    lat: 47.4996,
    lng: 19.0490,
    description: 'A Four Seasons étterme – visszafogott elegancia, erős ízek, reggeltől vacsoráig. Séf: Győrffy Árpád.',
    priceRange: '$$$$',
    rating: 4.6,
    isNew: false,
    yearInfo: '2015 óta',
    url: '',
    seafoodWarning: false
  },
  {
    id: 36,
    name: 'Apostolok Étterem',
    cuisine: 'Klasszikus magyar',
    mealTypes: ['lunch', 'dinner'],
    address: '1052 Budapest, Kigyó utca 4-6.',
    lat: 47.4940,
    lng: 19.0565,
    description: 'Több mint 120 éves legendás étterem, újjáéledt – klasszikus magyar konyha történelmi környezetben.',
    priceRange: '$$$',
    rating: 4.3,
    isNew: true,
    yearInfo: 'Újranyitott',
    url: '',
    seafoodWarning: false
  },

  // === DIÓSD / BUDAÖRS KÖRNYÉKE ===
  {
    id: 37,
    name: 'Fenyves Étterem',
    cuisine: 'Magyar',
    mealTypes: ['lunch', 'dinner'],
    address: 'Diósd',
    lat: 47.3959,
    lng: 18.9505,
    description: '1988 óta Diósd szívében – szezonális étlap, havi séfajánlatok, 60 fős kerthelyiség ősfás környezetben.',
    priceRange: '$$',
    rating: 4.2,
    isNew: false,
    yearInfo: '1988 óta',
    url: 'https://fenyvesetterem.hu/',
    seafoodWarning: false
  },
  {
    id: 38,
    name: 'Johnny\'s Bistro Diósd',
    cuisine: 'Bistro',
    mealTypes: ['lunch', 'dinner'],
    address: 'Diósd',
    lat: 47.3945,
    lng: 18.9480,
    description: 'Diósdi bistro – online rendelés, asztalfoglalás, catering is elérhető.',
    priceRange: '$$',
    rating: 4.0,
    isNew: false,
    yearInfo: 'Helyi',
    url: 'https://johnnys.hu/en/restaurants/diosd/',
    seafoodWarning: false
  },
  {
    id: 39,
    name: 'Fenyő Vendéglő',
    cuisine: 'Hagyományos magyar',
    mealTypes: ['lunch', 'dinner'],
    address: 'Budaörs',
    lat: 47.4613,
    lng: 18.9555,
    description: 'Kis gyöngyszem Budaörs csendes utcájában – ugyanaz a séf főz 40 éve, igazi régi ízek, bőséges adagok.',
    priceRange: '$',
    rating: 4.5,
    isNew: false,
    yearInfo: '40 éve működik',
    url: '',
    seafoodWarning: false
  },
  {
    id: 40,
    name: 'Fogadó a Magyar Királyokhoz',
    cuisine: 'Hagyományos magyar',
    mealTypes: ['lunch', 'dinner'],
    address: 'Budaörs',
    lat: 47.4600,
    lng: 18.9600,
    description: 'Két Mesterszakács vezeti – gasztronómia és magyar történelem találkozása. Elviteles ebéd is rendelhető.',
    priceRange: '$$',
    rating: 4.2,
    isNew: false,
    yearInfo: '2003 óta',
    url: 'https://www.magyarkiralyok.hu/',
    seafoodWarning: false
  },

  // === EXTRA AJÁNLATOK ===
  {
    id: 41,
    name: 'Vinyl & Wood',
    cuisine: 'Kávézó, lifestyle brunch',
    mealTypes: ['brunch'],
    address: 'Budapest, VII. kerület',
    lat: 47.4985,
    lng: 19.0640,
    description: 'Kávézó, reggeliző és lifestyle bolt – Cubano toast házi BBQ tépett sertéssel, shakshuka, különleges brunch.',
    priceRange: '$$',
    rating: 4.3,
    isNew: false,
    yearInfo: 'Népszerű',
    url: '',
    seafoodWarning: false
  },
  {
    id: 42,
    name: 'Arquitecto PitPit',
    cuisine: 'Spanyol, katalán',
    mealTypes: ['lunch', 'dinner'],
    address: 'Budapest, belváros (belső udvar)',
    lat: 47.4970,
    lng: 19.0560,
    description: 'Budapest egyik legszebb belső udvarában – katalán konyha: ökörfark, borjú-édesség, ceviche.',
    priceRange: '$$$',
    rating: 4.4,
    isNew: false,
    yearInfo: 'Felkapott',
    url: '',
    seafoodWarning: false
  }
];

// Default starting point: Diósd
const DEFAULT_ORIGIN = {
  name: 'Diósd, Magyarország',
  lat: 47.3959,
  lng: 18.9489
};
